/**
 * Gets the header comment for the CSS file.
 * @param {string} packageName - The name of the package.
 * @returns {string} The header comment.
 */
function getHeaderComment(packageName = "valcss") {
  const now = new Date();
  const timestamp =
    now.toISOString().split("T")[0] + " " + now.toTimeString().slice(0, 5);
  return `/* 
Generated by ${packageName} 
Last updated: ${timestamp} 
*/\n`;
}

module.exports = { getHeaderComment };
