/**
 * Gets the header comment for the CSS file.
 * @param {string} packageName - The name of the package.
 * @returns {string} The header comment.
 */
function getHeaderComment(packageName = "valcss") {
  const timestamp = new Date().toISOString();
  return `
/* 
Generated by ${packageName} 
Last updated: ${timestamp} 
*/\n`;
}

module.exports = { getHeaderComment };
